### ISSUE TITLE
I'd like to help finish off refactor-wip

### ISSUE THREAD

**Issue by giladbarnea** [tambien/Piano#13]
Hi,

Piano is at the core of an important project of mine (academic research about learning, cognitively).
I've been struggling with a bug lately. I'm not sure it has anything to do with Piano, but refactoring the code might vastly help me debug it.

I'm willing to help - I'm fairly familiar with the lib already, and by looking at the changes in the branch I think I can see what you're aiming at; at the very least, move to ES6, adapt the code to newer versions of the dependencies, write proper JSDoc etc.

It'd be smarter if I asked explicitly though - what are the goals of this branch, any points you'd like me to keep in mind, things to avoid etc?

Also, as you've put some effort JSDoc'ing function types, I'd happily convert some (all?) of the code to TypeScript, if you want.

Thanks,
Gilad

**Comment by tambien** [comment]
@giladbarnea that'd all be super helpful and very appreciated! the WIP branch was because i needed to move all my work from another computer and didn't want to lose anything, so i don't quite remember exactly where i left it off, but i think your observations are right.

As you mentioned, i was in the process of updating the dependencies to the latest Tone.js (which changed MultiSampler to Sampler and a few other changes) and a few other refactoring and API changes. 

I think a typescript conversion and some JSDocs would be really great and very helpful! 

going to close this, since it's not quite an issue, but feel free to follow up here, through PRs or email (yotam@tonejs.org)
